version: "3.9"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx 
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx-backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rentx
    depends_on:
      - database_rentx
  
volumes:
  pgdata:
    driver: local 